///
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import { Web3AuthSignerProvider } from "./components/contex/web3-auth-signer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3AuthSignerProvider>
          <div className="flex gap-2 ">
            <div className="fixed">
              <Sidebar />
            </div>
            <div className="container md:ml-80 ml-10">{children}</div>
          </div>
        </Web3AuthSignerProvider>
      </body>
    </html>
  );
}
